name: smartiotconnect
description: Connect ios device and configure
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dart_ping_ios: ^4.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.18.1
  logger: ^2.2.0
  network_tools: ^5.0.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  
  

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
