name: smartiotconnect
description: Connect ios device and configure
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_blue_plus: ^1.32.4
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  logger: ^2.2.0
  permission_handler: ^11.3.1
  rxdart: ^0.26.0
  shared_preferences: ^2.2.3
  soundpool: ^2.4.1
  
  

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
