name: smartiotconnect
description: Connect ios device and configure
version: 1.0.0+2
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  device_info_plus: ^10.1.0
  cloud_firestore: ^5.4.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_blue_plus: ^1.32.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  logger: ^2.4.0
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  soundpool: ^2.4.1
  csv: ^6.0.0
  firebase_ui_auth: ^1.15.0
  firebase_auth: ^5.2.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  
  

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  assets:
    - assets/sounds/
